discourse:
  image: codeformuenster/discourse
  ports:
    - "3000:3000"
  volumes:
    - discourse/assets:/usr/src/app/public/assets
    - discourse/uploads:/usr/src/app/public/uploads
    - discourse/backups:/usr/src/app/public/backups
  links:
    - postgres
    - redis
  env_file:
    - .env

sidekiq:
  image: codeformuenster/discourse
  command: sidekiq -c 3 -v
  links:
    - postgres
    - redis
  env_file:
    - .env
  volumes_from:
    - discourse

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=discourse
  env_file:
    - .env
  volumes:
    - ./data:/var/lib/postgresql/data

redis:
  image: redis:2.6
